export const charts = {
  0: "",
  1: "balances",
  2: "balances",
  3: "credit",
  4: "credit",
  5: "credit",
  6: "credit",
  7: "credit",
  8: "credit",
  9: "credit",
  10: "credit",
  11: "credit",
  12: "credit",
  13: "credit",
  14: "credit",
  15: "private credit",
  16: "private credit",
  17: "private credit",
  18: "weighted median"
};
