export const lectureRoutes = {
  heading: true,
  path: "",
  routes: [
    {
      id: 0,
      title: "Fundamentals",
      path: "/lectures/fundamentals",
      routes: [
        {
          id: 0,
          title: "Introduction",
          path: "/fundamentals/introduction",
          lectureId: 0,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 1,
          title: "Balance Sheets and Deposits",
          path: "/fundamentals/balance-sheets-and-deposits",
          lectureId: 0,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 2,
          title: "Deposit Transfers",
          path: "/fundamentals/deposit-transfers",
          lectureId: 0,
          keyTermsIds: [3, 4],
        },
        {
          id: 3,
          title: "Overdrafts",
          path: "/fundamentals/overdrafts",
          lectureId: 0,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 4,
          title: "Loans",
          path: "/fundamentals/loans",
          lectureId: 0,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 5,
          title: "Constraints",
          path: "/fundamentals/constraints",
          lectureId: 0,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 6,
          title: "Sandbox",
          path: "/fundamentals/sandbox",
          lectureId: 0,
          keyTermsIds: [0, 1, 2],
        },
      ],
    },
    {
      id: 1,
      title: "Towards a Central Bank",
      path: "/lectures/towards-a-central-bank",
      routes: [
        {
          id: 7,
          title: "Introduction",
          path: "/towards-a-central-bank/introduction",
          lectureId: 1,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 8,
          title: "One Big Bank",
          path: "/towards-a-central-bank/one-big-bank",
          lectureId: 1,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 9,
          title: "Multiple Banks",
          path: "/towards-a-central-bank/multiple-banks",
          lectureId: 1,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 10,
          title: "Correspondent Banking",
          path: "/towards-a-central-bank/correspondent-banking",
          lectureId: 1,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 11,
          title: "The Clearing House",
          path: "/towards-a-central-bank/the-clearing-house",
          lectureId: 1,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 12,
          title: "Clearing House Loans",
          path: "/towards-a-central-bank/clearing-house-loans",
          lectureId: 1,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 13,
          title: "Sandbox",
          path: "/towards-a-central-bank/sandbox",
          lectureId: 1,
          keyTermsIds: [0, 1, 2],
        },
      ],
    },
    {
      id: 2,
      title: "The Federal Reserve",
      path: "/lectures/the-federal-reserve",
      routes: [
        {
          id: 14,
          title: "Introduction",
          path: "/the-federal-reserve/introduction",
          lectureId: 2,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 15,
          title: "Daylight Overdrafts",
          path: "/the-federal-reserve/daylight-overdrafts",
          lectureId: 2,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 16,
          title: "The Fed Funds Market",
          path: "/the-federal-reserve/the-fed-funds-market",
          lectureId: 2,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 17,
          title: "Funding a Mortgage",
          path: "/the-federal-reserve/funding-a-mortgage",
          lectureId: 2,
          keyTermsIds: [0, 1, 2],
        },
        {
          id: 18,
          title: "Fed Funds Rate: Effective",
          path: "/the-federal-reserve/fed-funds-rate-1",
          lectureId: 2,
          keyTermsIds: [0, 1, 2],
        },
        // {
        //   id: 19,
        //   title: "Sandbox",
        //   path: "/the-federal-reserve/sandbox",
        //   lectureId: 2,
        //   keyTermsIds: [0, 1, 2],
        // },
      ],
    },
  ],
};
